port: 7890
socks-port: 7891
allow-lan: false
mode: rule
log-level: info
external-controller: 127.0.0.1:9090

proxies:

proxy-groups:
  - name: 节点选择
    type: select
    proxies:
      - 自动选择
      - 中国节点
      - 日本节点
      - 美国节点
      - 香港节点
      - 狮城节点
      - 其他国家
      - 负载均衡
      - YOUTUBE
      - TWITTER
      - GOOGLE
      - GITHUB
      - 失败切换
      - DIRECT
  - name: 美国节点
    type: url-test
    url: 'https://github.com/explore'
    interval: 300
    proxies:
  - name: 香港节点
    type: url-test
    url: 'https://github.com/explore'
    interval: 300
    proxies:
  - name: 中国节点
    type: url-test
    url: 'https://github.com/explore'
    interval: 300
    proxies:
  - name: 日本节点
    type: url-test
    url: 'https://github.com/explore'
    interval: 300
    proxies:
  - name: 狮城节点
    type: url-test
    url: 'https://github.com/explore'
    interval: 300
    proxies:
  - name: 其他国家
    type: url-test
    url: 'https://github.com/explore'
    interval: 300
    proxies:
  - name: 自动选择
    type: url-test
    url: 'https://github.com/explore'
    interval: 30
    tolerance: 100
    proxies:
  - name: YOUTUBE
    type: url-test
    url: 'https://www.youtube.com'
    interval: 60
    tolerance: 100
    proxies:
  - name: TWITTER
    type: url-test
    url: 'https://www.twitter.com'
    interval: 60
    tolerance: 100
    proxies:
  - name: GOOGLE
    type: url-test
    url: 'http://www.gstatic.com/generate_204'
    interval: 60
    tolerance: 100
    proxies:
  - name: GITHUB
    type: url-test
    url: 'https://github.githubassets.com/favicons/favicon.svg'
    interval: 60
    tolerance: 100
    proxies:
  - name: 负载均衡
    type: load-balance
    strategy: consistent-hashing
    url: https://github.com/explore
    interval: 30
    tolerance: 100
    proxies:
  - name: 失败切换
    type: fallback
    url: https://github.com/explore
    interval: 300
    tolerance: 100
    proxies:

rule-providers:
  Reject:
    type: http
    behavior: domain
    url: https://fastly.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/reject.txt
    path: ./ruleset/TopFreeProxies/reject.yaml
    interval: 86400

rules:
  - DOMAIN-KEYWORD,youtube,YOUTUBE
  - DOMAIN-KEYWORD,twitter,TWITTER
  - DOMAIN-KEYWORD,google,GOOGLE
  - DOMAIN-KEYWORD,github,GITHUB

  - RULE-SET,Reject,REJECT,no-resolve
  - MATCH,节点选择